### ISSUE TITLE
Error while accessing empty KV keys

### ISSUE THREAD

**Issue by mukhtharcm** [invertase/dart_edge#14]
While accessing non existing kv keys, currently it's throwing an error.
`Unhandled Promise Rejection: Error: TypeError: null: type 'JSNull' is not a subtype of type 'FutureOr<String>'`

I'm no expert in these, but a better idea would be to make the return type of `get` from kvNamespace from `Future<String>` to `Future<String?>` . Then we can check if the key exists by checking if the value is null.

**Comment by Ehesp** [comment]
Ah thanks, I'll sort that. Still trying to figure out how to properly test everything 😅

**Comment by mukhtharcm** [comment]
Thank you for the fast response!

**Comment by Ehesp** [comment]
Should be fixed here https://github.com/invertase/dart_edge/commit/f1dba9960570e1f2d4cc57b5ccf82257eaee12ac and in `0.0.2+2`
