### ISSUE TITLE
Provide out of the box `fetch` HttpOverride

### ISSUE THREAD

**Issue by Ehesp** [invertase/dart_edge#2]
The `fetch` API is very much a JavaScript concept, so for Dart developers it might be a bit confusing and not intuitive to use. It's most likely they'll reach for a library such as `dio` or `http`, however these all use the underlying [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) interface which isn't available on edge runtimes.

In theory, we can use a [HttpOverride](https://api.flutter.dev/flutter/dart-io/HttpOverrides-class.html) which internally uses the `fetch` API, and attach this as an override when using a provider. Then all Dart HTTP libraries should work as expected via the `fetch` API.

**Comment by MichealReed** [comment]
Curious how I can use this update, even on 0.0.2+1 I'm seeing 
```
Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html' show Blob, FormData, UrlSearchParams;
       ^
Info: The unavailable library 'dart:html' is imported through these packages:

    package:supabase_edge_functions_example => package:dart_openai => package:fetch_client => package:fetch_api => dart:html
```

**Comment by Ehesp** [comment]
There is an example on fetch in the documentation.

Other than that, it might be worth creating a new issue with a code example of what causes this error
